### ISSUE TITLE
串口2和spi冲突，不是串口3

### ISSUE THREAD

**Issue by flyleaf91** [Embedfire/embed_linux_tutorial#15]
![image](https://user-images.githubusercontent.com/3352200/84336467-e0696080-abc9-11ea-9138-3f6436cbe3ab.png)

串口2和spi冲突，不是串口3

**Comment by Jasonlixiaojian** [comment]
已修改成串口2

**Comment by Jasonlixiaojian** [comment]
已确认过并求改成串口2
