### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by LONGZR007** [Embedfire/embed_linux_tutorial#8]
在Linux系统中，信号可能是由于系统中某些错误而产生，也可以是摸个进程主动生成的一个信号。
这是https://tutorial.linux.doc.embedfire.com/zh_CN/latest/system_programing/signal.html#id3，其中：也可以是摸个->也可以是某个

**Comment by LONGZR007** [comment]
https://tutorial.linux.doc.embedfire.com/zh_CN/latest/system_programing/signal.html#id5，第二段的一些字变成了下标

**Comment by flyleaf91** [comment]
计算容量小节
![image](https://user-images.githubusercontent.com/3352200/82996147-20abd900-a037-11ea-8bc8-c44fc8eaa70f.png)

**Comment by flyleaf91** [comment]
修改使用的gitee源，不再使用wildfireteam下的，改用Embedfire下的，其它地方的做同样处理：


![image](https://user-images.githubusercontent.com/3352200/82996519-a9c31000-a037-11ea-8821-3907b1f05735.png)

**Comment by flyleaf91** [comment]
evtest的使用要加上sudo

![image](https://user-images.githubusercontent.com/3352200/83117784-16a1dd00-a100-11ea-986b-c42874f28148.png)

**Comment by flyleaf91** [comment]
![image](https://user-images.githubusercontent.com/3352200/83235469-81b4e780-a1c4-11ea-9e93-d008732c082e.png)

**Comment by flyleaf91** [comment]
makefile代码里需要加tab键
![image](https://user-images.githubusercontent.com/3352200/83470050-cb971980-a4b3-11ea-874b-24423208c554.png)

**Comment by flyleaf91** [comment]
![image](https://user-images.githubusercontent.com/3352200/83707604-f8326900-a64c-11ea-8939-c556d1771fa0.png)

**Comment by tulring** [comment]
这里文字错误
![748c111213a86c3d4613eb61e151fab](https://user-images.githubusercontent.com/43705702/83708482-f669a500-a64e-11ea-9f73-68e3efe870f2.png)

**Comment by tulring** [comment]
![748c111213a86c3d4613eb61e151fab](https://user-images.githubusercontent.com/43705702/83708545-1b5e1800-a64f-11ea-8a39-e2273437f21f.png)

**Comment by flyleaf91** [comment]
![image](https://user-images.githubusercontent.com/3352200/83933095-37d98c00-a7d8-11ea-85bf-c6034964c051.png)
控制蜂鸣器一章   31.2节   上图划线处  他们是指代led驱动  还是指代蜂鸣器驱动

**Comment by flyleaf91** [comment]
![image](https://user-images.githubusercontent.com/3352200/84096186-ddd50280-aa33-11ea-8a94-88710fcccdec.png)


33.4.1 实验代码分析

**Comment by flyleaf91** [comment]
![image](https://user-images.githubusercontent.com/3352200/84110951-72e9f280-aa58-11ea-8801-ba1d7904f46a.png)

![image](https://user-images.githubusercontent.com/3352200/84110964-7da48780-aa58-11ea-96de-40ed6bbcbb38.png)

**Comment by flyleaf91** [comment]
![image](https://user-images.githubusercontent.com/3352200/84113931-0ffb5a00-aa5e-11ea-8c65-2f5074f47ad4.png)

**Comment by Jasonlixiaojian** [comment]
已修改错别字且添加相应说明
