### ISSUE TITLE
ebf-gpiod missing

### ISSUE THREAD

**Issue by est-oliveryang** [Embedfire/embed_linux_tutorial#9]
I'm using your EBF6ULL Pro development board and trying to install the gpio library you provided. Unfortunately, something went wrong.
![image](https://user-images.githubusercontent.com/56299169/82517278-56d8ec80-9b4f-11ea-8fe0-5692ff71d92b.png)
![image](https://user-images.githubusercontent.com/56299169/82517499-d8c91580-9b4f-11ea-946c-644cfc9ed304.png)

Would you please solve the issue. Thanks.

**Comment by flyleaf91** [comment]
> I'm using your EBF6ULL Pro development board and trying to install the gpio library you provided. Unfortunately, something went wrong.
> ![image](https://user-images.githubusercontent.com/56299169/82517278-56d8ec80-9b4f-11ea-8fe0-5692ff71d92b.png)
> ![image](https://user-images.githubusercontent.com/56299169/82517499-d8c91580-9b4f-11ea-946c-644cfc9ed304.png)
> 
> Would you please solve the issue. Thanks.

the source of wildfireteam.gitee are invalid，use github source instead:

open sources.list file:
`sudo vi /etc/apt/sources.list`

find：

`deb [arch=armhf] https://Wildfilreteam.gitee.io/ buster main`

replace with：

`deb [arch=armhf] https://Embedfire.github.io/ buster main`

save file,and then:
`sudo apt update`
